### ISSUE TITLE
Building Error list.tcc

### ISSUE THREAD

**Issue by Merry93** [RSATom/QmlVlcDemo#5]
Hello,

I am having a problem when building the QmlVlc Demo with Qt 5.3.2, Qt Creator 3.2.1 and Mingw 4.8.2 32Bit. When Compiling I always get the following Error: D:\Programming\Qt\Qt5.3.2\Tools\mingw482_32\i686-w64-mingw32\include\c++\bits\list.tcc:248: Fehler: no match for 'operator==' (operand types are 'QVideoFrame' and 'const value_type {aka const QVideoFrame}')
![image](https://cloud.githubusercontent.com/assets/13473872/8861759/7b36895c-318c-11e5-89a9-6a27ba8cc9d1.png)

I have VLC installed and set in the Path Variable and cloned the Git Repository with --recursive. Do you have any Idea what could be the Problem?

Thank you for your help and for creating and sharing this project!

**Comment by RSATom** [comment]
Any specific reason why do you use outdated Qt version?

**Comment by Merry93** [comment]
It is for a bigger project which is just being updated to use Qt 5.4.2, so it would be nice to use it on 5.3.2 or 5.4.2.

I tried compiling it with 5.4.2 (MinGW 4.9.1) but it gives the same Error. I also tried Qt 5.5 (MinGW 4.9.2) and it works perfectly.
I suppose it hast something to do with the m_videoFrames list in QmlVlcMmVideoOutput.cpp but I´m not sure.

**Comment by RSATom** [comment]
I've tried myself build it with Qt 5.2.1 and found I've broke compatibility with Qt version older than 5.5 by my latest commits related to Android support. So it's definitely regression. I'll try to fix it soon. Thanks for pointing it.

**Comment by Merry93** [comment]
Thank you for the help. 
Since I don´t really need the VlcMmPlayer (I just use VlcPlayer) i commented out everything related to QmlVlcMmPlayer and now it is compiling succesfully. So for now this could be a Workaround for older Versions of Qt.

**Comment by RSATom** [comment]
All QtMultimedia related stuff will be disabled in `QmlVlc` if you will not add QtMultimedia dependency before including `QmlVlc.pri`

**Comment by PeterKieu** [comment]
Please fix bug for building on Qt 5.4: Error: no match for 'operator==' (operand types are 'QVideoFrame' and 'const value_type {aka const QVideoFrame}')
I cannot upgrade to Qt 5.5 due to my target binary system based on Qt 5.4 on Linux.
Thanks

**Comment by RSATom** [comment]
@PeterKieu, Are you sure need compatibility with Qt 5.4? Maybe with Qt 5.2? What Linux distribution do you use?

**Comment by PeterKieu** [comment]
Thank you for your fast response.
I run Tizen Linux IVI 3.0 version on intel NUC (Qt 5.4), and I would like to run on Tizen Mobile soon.
My target is using your solution for my DIY DVB-T2 tivi box server using libvlc core. 
For Qt 5.5, I built QmlVlcDemo successfully but it only runs on Ubuntu.
Please help!

**Comment by RSATom** [comment]
@PeterKieu, ok, I'll fix it at this week.

**Comment by PeterKieu** [comment]
So GREAT!
Now, we can build well on Qt 5.4. The demo runs fast.
Thanks much S Radionov!
