### ISSUE TITLE
OSX installation?

### ISSUE THREAD

**Issue by VirusKA** [RSATom/QmlVlcDemo#6]
Excuse me, is there a way to download this demo on OSX? I would like to try this out!

**Comment by RSATom** [comment]
1. Install VLC
2. Install Qt
3. run `git clone --recursive https://github.com/RSATom/QmlVlcDemo.git`
4. open `QmlVlcDemo.pro` in QtCreator and build

something like this

**Comment by VirusKA** [comment]
oh ok thanks
