### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by berkantay** [RSATom/QmlVlcDemo#8]
I succesfully build your project. However qmlvlcdemo implementation crashes.

QmlVlcDemo: ../QmlVlcDemo/deps/QmlVlc/QmlVlcVideoOutput.cpp:97: void QmlVlcVideoOutput::init(): Assertion `m_player && m_player->is_open()' failed.

**Comment by RSATom** [comment]
I think it just was not able load libvlc by some reason.

**Comment by berkantay** [comment]
Got it, have you got any example code snippet for rtsp streaming (client) for qt. I would be appreciated if you share with me.
email:berkantay.5@gmail.com

**Comment by RSATom** [comment]
No, I don't have example for rtsp, but it will be identical as to any other url type. Just replace url in demo to rtsp url.

**Comment by berkantay** [comment]
First error is disappeared by installing ```vlc-plugin-qt``` package from ubuntu. But window remains grey and nothing shows up for rtsp link.

**Comment by RSATom** [comment]
@berkantay Do you see something in console?

**Comment by berkantay** [comment]
No warnings no errors  shows up on the console.

**Comment by RSATom** [comment]
Are you able run Vlc itself?

**Comment by berkantay** [comment]
Yes vlc itself is able to run the link.

**Comment by RSATom** [comment]
Do you see at least something in console?

**Comment by berkantay** [comment]
Here is the screenshot of the desktop https://ibb.co/wQWmNsN

**Comment by RSATom** [comment]
I don't see terminal window there...
Can you try run it directly from terminal?

**Comment by berkantay** [comment]
Sorry I get ```Project ERROR: Unknown module(s) in QT: multimedia``` error on the terminal. Here is the screenshot. https://ibb.co/zRq6DxC

**Comment by RSATom** [comment]
It looks like you didn't install some required Qt packages. I don't remember what exactly packages it required - you have to find it yourself.

**Comment by berkantay** [comment]
Problem solved @RSATom thank for your support, cheers.

**Comment by berkantay** [comment]
Installed ```qt5multimedia-dev```

**Comment by berkantay** [comment]
Have you got any idea about setting the network caching parameter.

**Comment by RSATom** [comment]
You can try run `vlc --longhelp` to get info about options.
